### ISSUE TITLE
AQI calculation seems broken

### ISSUE THREAD

**Issue by yegle** [wbertelsen/purpleair-to-prometheus#3]
If I print the exception it looks like this:

```
Traceback (most recent call last):
  File "./purple_to_prom.py", line 144, in <module>
    main()
  File "./purple_to_prom.py", line 140, in main
    poll(args.sensor_ids, args.refresh_seconds)
  File "./purple_to_prom.py", line 123, in poll
    raise e
  File "./purple_to_prom.py", line 119, in poll
    check_sensor(sensor_id)
  File "./purple_to_prom.py", line 93, in check_sensor
    i_aqi_LRAPA = aqi.to_iaqi(aqi.POLLUTANT_PM25, pm25_10min_LRAPA, algo=aqi.ALGO_EPA)
  File "/home/yegle/git/purpleair-to-prometheus/venv/lib/python3.7/site-packages/aqi/__init__.py", line 33, in to_iaqi
    return _aqi.iaqi(elem, cc)
  File "/home/yegle/git/purpleair-to-prometheus/venv/lib/python3.7/site-packages/aqi/algos/base.py", line 93, in iaqi
    (aqilo, aqihi) = self.piecewise['aqi'][idx]
IndexError: list index out of range
```

**Comment by wbertelsen** [comment]
I wonder what `pm25_10min_LRAPA` was at the time that this broke. It might have gone out of the range that makes sense for aqi (like below zero)

**Comment by yegle** [comment]
Hmm, this does fix the issue.

FWIW, if you want to reproduce: checkout v0.0.3 and run the script wit sensor id 64745.

**Comment by wbertelsen** [comment]
@yegle the air is just too good today I guess
